### ISSUE TITLE
doc: move 'Requirements' section to the first place before 'Versions' section

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/rhel-s2i-nodejs#3]
Context:
Few days ago I installed fedora 26 again, then I have no `docker-squash` neither `s2i`.

Then would be good to have the `Requirements` section first on the README.md, also to include `s2i`.

**Comment by lance** [comment]
I don't actually want the build information to be at the top, because ideally most consumers of this will be pulling from docker hub or some other docker registry, instead of building directly.

**Comment by helio-frota** [comment]
Yah makes sense :+1:
